### ISSUE TITLE
Issues for importing reality

### ISSUE THREAD

**Issue by Graveyard9988** [maskedeken/Matsuri#1]
I can not import this config via your plugin:

vless://LegenderY_Servers@45.76.42.162:125?mode=gun&security=reality&encryption=none&pbk=aDCEkPhIjjfU1RODapItIVmTq9rLn3YWUwy1kiIJ9Sc&fp=chrome&type=grpc&serviceName=ARSHAM.6IX&sni=github.io#Tel%3A%40Amir_Alternative_Official

Or I can not I add it manually! Please check this

**Comment by maskedeken** [comment]
please check [https://github.com/maskedeken/plugins/suites/11823850835/artifacts/617545846](https://github.com/maskedeken/plugins/suites/11823850835/artifacts/617545846)

**Comment by Graveyard9988** [comment]
After importing I face with this issue 
And I can't add it manually too
![Screenshot_20230329_153004_Matsuri](https://user-images.githubusercontent.com/116078041/228529080-68510c8b-499c-4736-90cf-eb14a3aa1dec.jpg)

**Comment by maskedeken** [comment]
try this [https://github.com/maskedeken/plugins/releases/tag/Xray-v1.8.0-4](https://github.com/maskedeken/plugins/releases/tag/Xray-v1.8.0-4)

**Comment by Graveyard9988** [comment]
![Screenshot_20230330_083658_Matsuri](https://user-images.githubusercontent.com/116078041/228735051-84a7b663-5a24-4e23-b3ee-94712a3fb96d.jpg)

After importing, problem is still existing

See image please 

Here's config:
vless://LegenderY_Servers@45.76.42.162:125?mode=gun&security=reality&encryption=none&pbk=aDCEkPhIjjfU1RODapItIVmTq9rLn3YWUwy1kiIJ9Sc&fp=chrome&type=grpc&serviceName=ARSHAM.6IX&sni=github.io#Tel%3A%40Amir_Alternative_Official

**Comment by Graveyard9988** [comment]
Matsuri 0.6.2 + your latest plugin xray

**Comment by maskedeken** [comment]
check this out [https://github.com/maskedeken/plugins/suites/11907711701/artifacts/623414554](https://github.com/maskedeken/plugins/suites/11907711701/artifacts/623414554)

**Comment by Graveyard9988** [comment]
Imported!
There's another question 

![Screenshot_20230330_100311_NekoBox](https://user-images.githubusercontent.com/116078041/228749724-e8f873f9-8372-4ad5-99b5-46ac76f7a872.jpg)

Should be a "reality" option in the above image?

**Comment by maskedeken** [comment]
> 

this is not my plugin, u should submit an issue to NekoBox author

**Comment by maskedeken** [comment]
> > 
> 
> this is not my plugin, u should submit an issue to NekoBox author



this seems not my plugin, u should submit an issue to NekoBox author

**Comment by maskedeken** [comment]
> Imported! There's another question
> 
> ![Screenshot_20230330_100311_NekoBox](https://user-images.githubusercontent.com/116078041/228749724-e8f873f9-8372-4ad5-99b5-46ac76f7a872.jpg)
> 
> Should be a "reality" option in the above image?

this seems not my plugin, u should submit an issue to NekoBox author

**Comment by Graveyard9988** [comment]
Sorry I made a mistake for sending screenshot

**Comment by Graveyard9988** [comment]
There's another issue

Utls "chrome" have not imported from link at matsuri

**Comment by Graveyard9988** [comment]
Please re-open

**Comment by maskedeken** [comment]
> There's another issue
> 
> Utls "chrome" have not imported from that reality link at matsuri

this will work [https://github.com/maskedeken/plugins/suites/11908624801/artifacts/623473926](https://github.com/maskedeken/plugins/suites/11908624801/artifacts/623473926)

**Comment by Graveyard9988** [comment]
Thanks sir! Great job
It works 🙏🏻
