### ISSUE TITLE
Trojan Reality issue (import)

### ISSUE THREAD

**Issue by Graveyard9988** [maskedeken/Matsuri#2]
This trojan Reality node can't be imported correctly:

trojan://ARSHAM.6IX@70.34.208.112:443?mode=multi&security=reality&fp=chrome&type=grpc&serviceName=&sni=github.io#XD
pub key=9pbjbWx5ZTFPWtg2IvJqCLDdjtNjNRfRTvRJXUoG6mM

![Screenshot_20230331_223414_Matsuri](https://user-images.githubusercontent.com/116078041/229207700-b71a3f06-0dab-4fa8-a377-ec72de3dfedd.jpg)

**Comment by maskedeken** [comment]
Matsuri is based on v2ray-core which dose not support reality protocol, so it won't fix

**Comment by Graveyard9988** [comment]
Thanks
I thought that Reality is related to xray core and it could be resolvable
