### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by Graveyard9988** [maskedeken/Matsuri#3]
I Uninstalled main matsuri but your fork does not install!

Android 13 - arm64v8

**Comment by maskedeken** [comment]
please provide the screen capture

**Comment by Graveyard9988** [comment]
![Screenshot_20230605_081555_Package installer](https://github.com/maskedeken/Matsuri/assets/116078041/7dcf4fac-6299-48e7-b5c6-a2d0c0a2cf67)

**Comment by Graveyard9988** [comment]
I cleared data of main matsuri then uninstalled it, but still can't install your latest fork with newest core

**Comment by maskedeken** [comment]
seems that old matsuri was not removed completely

**Comment by Graveyard9988** [comment]
I removed it completely with clearing data of it before uninstalling

**Comment by Graveyard9988** [comment]
I'd be grateful if you could change some parameters like signature or another way to resolve this issue

**Comment by Graveyard9988** [comment]
I restarted my phone but doesn't make any difference

**Comment by Graveyard9988** [comment]
@maskedeken 🙏🏻

**Comment by maskedeken** [comment]
> @maskedeken 🙏🏻

Maybe you could try it on another phone

**Comment by Graveyard9988** [comment]
I have another phone and it's the same

**Comment by Graveyard9988** [comment]
![Screenshot_20230615_084104_Package installer](https://github.com/maskedeken/Matsuri/assets/116078041/3d71f5c5-c1e1-4b1f-bf95-9fb981cee2e9)
Again! With newest apk file from actions tab

**Comment by maskedeken** [comment]
> 

maybe u should build your own app with a different package name

**Comment by Graveyard9988** [comment]
I fixed it
But your Naiive plugin isn't appeared at plugin section to enable it

**Comment by maskedeken** [comment]
> I fixed it But your Naiive plugin isn't appeared at plugin section to enable it

Naive plugin is not Advanced plugin, so no need to enable it

**Comment by Graveyard9988** [comment]
Thanks a lot
